### ISSUE TITLE
datapackage_init should have an output path parameter

### ISSUE THREAD

**Issue by scls19fr** [christophergandrud/dpmr#13]
Hello,

I'm trying dpmr to create automatically several datapackages.
but it seems that `datapackage_init` doesn't have an output path parameter.
It will be nice to provide such a feature.
A workaround is to use `setwd(...)` but that's not very convenient

Kind regards

**Comment by christophergandrud** [comment]
Thanks for the idea. It's now in the current dev build (5448cef04f2e83a489e3d513d52b81a73fc3d9d8), so give it a shot and see if there are any bugs.

**Comment by scls19fr** [comment]
Ok. Thanks I will have a look at this.
