### ISSUE TITLE
Install data package from url

### ISSUE THREAD

**Issue by rgrp** [christophergandrud/dpmr#4]
Most standard setup for a data package is for it to live (unzipped) at a URL. This is the setup for the Data Packages on http://data.okfn.org/data/

To load these you just need to:

* Load datapackage.json
* To load data in resources
  * if url is present use it to load data
  * if no url but path use path to resolve relative to datapackage.json ...

**Comment by rgrp** [comment]
@christophergandrud no problem - any ideas on timeline? Also would you be able to help others if I could find some other R folks to help out?

**Comment by christophergandrud** [comment]
I have a load of things due by 15 January. After that I should have more time.

I'm actually thinking of reworking the internals of the package. Currently it mirrors datapackage's capabilities written in R. But perhaps a better way to go is to pass work directly to dpm, e.g. 

```{S}
datapackage_init <- function(data, name) {
    write.csv(data, file = paste0(name, '.csv'), row.names = TRUE)
    
    sys_call <- paste("dpm init", name)
    system(sys_call)
}
```

The downside of this is that it increases dependencies. On the upside it would keep the two implementations in sync better and reduce duplicated work.

Thoughts?

**Comment by rgrp** [comment]
@christophergandrud my sense is that at least for install and publishing stuff is so simple that having it only depend on R would be good (and increase usage by pure R users). Installing dpm requires node etc etc.

**Comment by christophergandrud** [comment]
That's true.

**Comment by christophergandrud** [comment]
Finally got around to finishing off v0.1.

Just need to implement some tests before sending it to CRAN.

If interested  test installing from https:

```r
devtools::install_github('christophergandrud/dpmr')
library(dpmr)

URL <- 'https://github.com/datasets/gdp/archive/master.zip'
gdp_data <- datapackage_install(path = URL)
```

The README has some other examples.
